version: "3.5"
services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.8.1
        hostname: elasticsearch
        environment:
            - discovery.type=single-node
            - ES_JAVA_OPTS="-Xms8g -Xmx8g"
        ports:
            - "9200:9200"

    kibana:
        image: docker.elastic.co/kibana/kibana:7.8.1
        hostname: kibana
        environment:
          - NODE_OPTIONS="--max-old-space-size=4096"
        depends_on:
            - elasticsearch
        ports:
            - "5601:5601"

